### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by satlylord** [qbcore-framework/qb-core#327]
**Describe the bug**
Playerdata saved to the database is duplicated from what I believe is the "QBCore.Player.Save" function. Since this function uses "INSERT" instead of "UPDATE" new data is constantly saved to the database rather then updating the existing data.  

**To Reproduce**
1. Simply sign in and wait for the playerdata to update

**Expected behavior**
On the client side in loops.lua, every time the CitizenThread for UpdateInterval ticks it triggers "QBCore:UpdatePlayer". Which then saves your data using QBCore.Player.Save.

**Questions (please complete the following information):**
 - Last update 11-10-21
 - No
 - No

**Additional context**
I see that there is a statement in the SQL for duplicate entries but it doesn't appear to be working. Any insight would be great.

**Comment by jnccloud** [comment]
What is your primary key in your `players` table? A few weeks ago the primary key was updated to `citizenid` instead of `id`. The update to qb-core was mentioned as a breaking update in the Discord and you have to update your database to prevent the duplication issue.

On my server, I tested and ran the following statements. **You will need to clean up the duplicate records before this will work though as `citizenid` cannot be the primary key in a table if there are duplicate records.** So if you've updated your live server you will **_need_** to spend some time removing the older records. So DEFINITELY **create a database backup before** you change perform any queries I have listed below. Even copy the `players` table to a new table like `players_backup` so you can revert if needed easily by renaming the table. If you compare the oldest record with the newest from one player, you can validate that the data is correct in the newest one. The only piece that changes is the id and updated metadata on the record.

```mysql
ALTER TABLE players DROP PRIMARY KEY;
ALTER TABLE players ADD KEY (`id`);
ALTER TABLE players ADD PRIMARY KEY (`citizenid`);
```

If you want to identify all of the duplicate records from every player without the LATEST player record:

```mysql
SELECT * FROM players
INNER JOIN (
SELECT MAX(id) AS lastId, citizenid
FROM players
GROUP BY citizenid
HAVING COUNT(*) > 1) duplic ON duplic.citizenid = players.citizenid
WHERE players.id < duplic.lastId;
  ```

If you want to see the NEWEST records and exclude the original, oldest record (will be outdated from the latest saved playerdata update):

```mysql
SELECT * FROM players
INNER JOIN (
SELECT MIN(id) AS lastId, citizenid
FROM players
GROUP BY citizenid
HAVING COUNT(*) > 1) duplic ON duplic.citizenid = players.citizenid
WHERE players.id > duplic.lastId;
```

Use these queries at your own risk. I am not responsible for anything that results from using them.

**Comment by satlylord** [comment]
Ahhh!! That would be the issue! My primary key is set to the id and not citizenid. I'm not part of the discord so I must've missed this.  Lucky for me this is just our beta version so just a quick wipe and changing the key should fix this issue. Thank you!
