### ISSUE TITLE
[BUG] attempt to index a nil value (field 'Vehicles') and attempt to index a nil value (local 'Player)

### ISSUE THREAD

**Issue by FizzGamingJR** [qbcore-framework/qb-core#495]
**Describe the bug**
I recently added new vehicles to the vehicles.lua for the PDM, after doing so I received an error from qb-core saying "attempt to index a nil value (field 'Vehicles'). Shortly after receiving this error I also began seeing "attempt to index a nil value (local 'Player')" in the console. This caused many other problems with other qb scripts but will not list them here. I have attempted to update qb-core, update the .lua to default state, and update oxmysql.

**To Reproduce**
1. Unknown what causes this.

**Expected behavior**
qb-core is not meant to produce errors in the console.

**Screenshots**
https://prnt.sc/26ewd6m
(Unable to produce screenshot for other error, mainly pops up now when attempting to purchase vehicles or open AdminMenu)

**Questions (please complete the following information):**
 - When you last updated: Today
 - Are you using custom resource? which ones? None
 - Have you renamed `qb-` to something custom? No, I kept it qb-core

**Additional context**
N/A

**Comment by Sable-20** [comment]
just to save people who know lua a bit better than me

line 152 of `server/events.lua` is 

```lua
TriggerClientEvent('hud:client:UpdateNeeds', src, Player.PlayerData.metadata['hunger'], Player.PlayerData.metadata['thirst'])
```

which is a bit confusing to me cause it seems vehicles should have no place in here

there seems to be a issue somewhere where they likely added something somewhere they should not have or did not apply patches or something, because this is causing an issue with the player class itself, id look into the player class and how its updating things

**Comment by FizzGamingJR** [comment]
Just an update on this, I found a fix to my issues. I apologise about wasting anybody's time. At the top of my console I missed a vital error, I ended up fixing this by saving the vehicles.lua document In VSC as UTF-8. I believe it was an encoding error or something on these lines. Thank you.
