### ISSUE TITLE
[BUG] Not letting get into the server "We are checking your allowance"

### ISSUE THREAD

**Issue by XD-Specs7** [qbcore-framework/qb-core#609]
Keep getting stuck on "We are checking your allowance" when I try to get into the server. My database works fine so idk what the issue is, pls help :(
![Screenshot (124)](https://user-images.githubusercontent.com/65673153/160943158-18b9eeaf-a090-4ad7-91bc-c00f76311adf.png)

**Comment by ValyxFPS** [comment]
Same issue. Assuming that you're locally hosting this server my assumption is that something went wrong while port forwarding. This happened to me after i port forwarded. I am still looking for a fix. If I find something I will let you know.

**Comment by ValyxFPS** [comment]
After some investigation port forwarding is not the issue. I stopped the qb-core resource and it allowed me to connect to the server for now. Going to dig deeper and post more updates here.

**Comment by Monkey1995** [comment]
im having this also, like @ValyxFPS once stopping the qbcore resource it will then let me access.

**Comment by ValyxFPS** [comment]
@Monkey1995 Hello, please make sure that you dont have vMenu installed. This is what randomly caused the issue for me. Let me know how that goes. It seemed to be interacting with something in the core or permissions.

**Comment by roobr** [comment]
```
    local isBanned, Reason = QBCore.Functions.IsPlayerBanned(src)
    local isLicenseAlreadyInUse = QBCore.Functions.IsLicenseInUse(license)
    local isWhitelist, whitelisted = QBCore.Config.Server.Whitelist, QBCore.Functions.IsWhitelisted(src)
```

It will be something to do with a DB query most likely like when checking if whitelisted or banned etc most likely

**Comment by smurfgaming** [comment]
I had same issue, disabled QB core and it was fine

**Comment by ItsANoBrainer** [comment]
> I had same issue, disabled QB core and it was fine
> 

My toilet is clogged, I got rid of the toilet and it resolved the issue.

**Comment by lvto2000** [comment]
Having the same issue.  Removed QB-Core and works but agree with ItsANoBrainer, that option is pretty unhelpful.  Looked further in code and this note seems to come from a series of whitelisting conditional statements that check white listing, connectqueue and another setting.   I thought it might be the que since my server console claimed that the user was in queue.  That revealed a small note of progress then right back to "We are checking your allowance".   Sorry to be negative but the documents for QBCORE are horrible.

**Comment by lvto2000** [comment]
> ```
>     local isBanned, Reason = QBCore.Functions.IsPlayerBanned(src)
>     local isLicenseAlreadyInUse = QBCore.Functions.IsLicenseInUse(license)
>     local isWhitelist, whitelisted = QBCore.Config.Server.Whitelist, QBCore.Functions.IsWhitelisted(src)
> ```
> 
> It will be something to do with a DB query most likely like when checking if whitelisted or banned etc most likely

What should we be checking where in the DB?  My DB is empty.  I checked most of the tables.

**Comment by lvto2000** [comment]
> Keep getting stuck on "We are checking your allowance" when I try to get into the server. My database works fine so idk what the issue is, pls help :( ![Screenshot (124)](https://user-images.githubusercontent.com/65673153/160943158-18b9eeaf-a090-4ad7-91bc-c00f76311adf.png)

Just curious, did you set up an Other/Home server or did you select Dedicated server in your setup?

**Comment by ItsANoBrainer** [comment]
Maybe someone having the issue can do some self debugging? Throw prints into the code and see where it's getting held up.

**Comment by ValyxFPS** [comment]
Are you guys using vMenu? I installed vMenu and this was my issue right after. Uninstalling it worked.

**Comment by ValyxFPS** [comment]
vMenu is trash and horribly optimized anyways, man much better alternatives

**Comment by lvto2000** [comment]
Ok I found what the issue was in my case.  It was OxMySQL.  I did not realize that it was throwing up an error during the start of the system.  So pay close attention to every error you see when you start the FiveM server.   I get accustomed to seeing an error or two in the start so I missed this one.  In any case here was my fix.  I kept getting INVALID URL errors from OxMySQL.  Turns out that error was the issue but it was not very clear why it was an error.  Then I took a look at this page.  
               
         **LINK:** https://overextended.github.io/oxmysql/issues/

The first solution on that page fixed my problem.   I had included special RESERVED characters in my MariaDB password, instead of using the blank password that the standard install wants you to use.  In my case I am running a Linux version.  I removed the special reserved character in my password and then restarted the server.  Everything works now.  Make sure you change your Mysql/MariaDB password for the user you are using to update the database (if not the default root user).  Problem solved.  

Overall the error handling and reporting for many of these resources are not great.  Anyway, hope this helps the next person save the 2 days of troubleshooting I did to find this.

**Comment by izMystic** [comment]
> vMenu is trash and horribly optimized anyways, man much better alternatives

vMenu is actually very optimized for all the stuff that's in it, and the only reason it's high on the resource monitor (which basically doesn't mean anything) is because it's C#

**Comment by sparki4** [comment]
> Are you guys using vMenu? I installed vMenu and this was my issue right after. Uninstalling it worked.

the what to use?
or not to use at all idk

**Comment by musictomy** [comment]
Disabled qbcore and it worked for me

**Comment by Showtime4201** [comment]
quit fivem, and it worked for me ;) lol

**Comment by maejok-xx** [comment]
> Ok I found what the issue was in my case. It was OxMySQL. I did not realize that it was throwing up an error during the start of the system. So pay close attention to every error you see when you start the FiveM server. I get accustomed to seeing an error or two in the start so I missed this one. In any case here was my fix. I kept getting INVALID URL errors from OxMySQL. Turns out that error was the issue but it was not very clear why it was an error. Then I took a look at this page.
> 
> ```
>      **LINK:** https://overextended.github.io/oxmysql/issues/
> ```
> 
> The first solution on that page fixed my problem. I had included special RESERVED characters in my MariaDB password, instead of using the blank password that the standard install wants you to use. In my case I am running a Linux version. I removed the special reserved character in my password and then restarted the server. Everything works now. Make sure you change your Mysql/MariaDB password for the user you are using to update the database (if not the default root user). Problem solved.
> 
> Overall the error handling and reporting for many of these resources are not great. Anyway, hope this helps the next person save the 2 days of troubleshooting I did to find this.

Boy do I feel stupid..... but this was it. 🤣
