### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by NonameCommunity** [qbcore-framework/qb-core#847]
### Summary

I still get my paycheck even if there is no money in the company

### Reproduction

all original I have not changed anything

### Expected behavior

I don't get my paycheck because the company has no money

### Actual behavior

I get my paycheck even if the company has no money

### Additional context

is a basic core problem even downloading it again doesn't change anything

### Last Updated

no update

### Custom Resources

no custom resource

### Resource Rename

no

**Comment by JustCarry** [comment]
Hello NonameCommunity,

Can you confirm the job name you are currently getting paid for it?

Otherwise, please make sure you add the job in the management_funds and set the balance to `1` to make sure it doesn't pay when it doesn't have the sufficient amount. [Click here for reference](https://github.com/qbcore-framework/qb-management#you-need-to-create-a-row-in-database-with-name-of-society-in-management_funds-table-if-you-have-custom-jobs--gangs)

**Comment by NonameCommunity** [comment]
ok I had to put 1 on the database now it works thanks
